### ISSUE TITLE
numba error when running abacusHOD example

### ISSUE THREAD

**Issue by danecross** [abacusorg/abacusutils#159]
When I try to run the abacusHOD code on the simulation `AbacusSummit_base_c000_ph000` in NERSC, I get an error that says that a built-in function is not implemented. 

### Current setup: 
I have a fresh anaconda environment on NERSC, where I installed the basic abacusutils (without `classy` and `Corrfunc`) and then separately installed Corrfunc via `python -m pip install Corrfunc`. 

### Steps that lead to the error:

This is the config file I am using: [config.txt](https://github.com/user-attachments/files/17728507/config.txt) (note that I changed the file extension to .txt but if you want to reproduce the error you should change it back to .yaml ... github doesn't allow uploading files with strange extensions)

This is the code I am using to run the abacusHOD (ripped basically straight from the tutorial): [run_abHOD.txt](https://github.com/user-attachments/files/17728538/run_abHOD.txt) (again, if you want to run it, probably change the extension from .txt to .py)

1. run `python -m abacusnbody.hod.prepare_sim --path2config config.yaml` <-- this runs fine
2. run `python run_abHOD.py` <-- this gives the error

### The error

This is the full error I get when I run it:
```
~/ABACUS/HOD> python run_abHOD.py 
/global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py:1504: UserWarning: NFW profile is unoptimized. It has different velocity bias. It does not support lightcone.
  warnings.warn(
Traceback (most recent call last):
  File "/global/u2/d/dncross/ABACUS/HOD/run_abHOD.py", line 29, in <module>
    mock_dict = newBall.run_hod(newBall.tracers, want_rsd, write_to_disk, Nthread = 16)
  File "/global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/abacus_hod.py", line 759, in run_hod
    mock_dict = gen_gal_cat(
  File "/global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py", line 1661, in gen_gal_cat
    HOD_dict = gen_gals(
  File "/global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py", line 1507, in gen_gals
    LRG_dict_sat, ELG_dict_sat, QSO_dict_sat, ID_dict_sat = gen_sats_nfw(
  File "/global/homes/d/dncross/.conda/envs/abacus/lib/python3.10/site-packages/numba/core/dispatcher.py", line 423, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/global/homes/d/dncross/.conda/envs/abacus/lib/python3.10/site-packages/numba/core/dispatcher.py", line 364, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(none, int64)
 
There are 22 candidate implementations:
   - Of which 22 did not match due to:
   Overload of function 'getitem': File: <numerous>: Line N/A.
     With argument(s): '(none, int64)':
    No match.

During: typing of intrinsic-call at /global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py (503)

File "../opt/abacusutils/abacusnbody/hod/GRAND_HOD.py", line 503:
def compute_fast_NFW(
    <source elided>
            else:
                while NFW_draw[ind] > c[i]:
                ^

During: resolving callee type: type(CPUDispatcher(<function compute_fast_NFW at 0x7f2a339f79a0>))
During: typing of call at /global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py (713)

During: resolving callee type: type(CPUDispatcher(<function compute_fast_NFW at 0x7f2a339f79a0>))
During: typing of call at /global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py (737)

During: resolving callee type: type(CPUDispatcher(<function compute_fast_NFW at 0x7f2a339f79a0>))
During: typing of call at /global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py (761)

During: resolving callee type: type(CPUDispatcher(<function compute_fast_NFW at 0x7f2a339f79a0>))
During: typing of call at /global/u2/d/dncross/ABACUS/opt/abacusutils/abacusnbody/hod/GRAND_HOD.py (713)


File "../opt/abacusutils/abacusnbody/hod/GRAND_HOD.py", line 713:
def gen_sats_nfw(
    <source elided>
    h_id_L, x_sat_L, y_sat_L, z_sat_L, vx_sat_L, vy_sat_L, vz_sat_L, M_L = (
        compute_fast_NFW(
        ^
```

Any help would be greatly appreciated. Thanks in advance!

**Comment by lgarrison** [comment]
Hi @danecross, thank you for opening this issue. It looks like you found a bug in the tutorial! Specifically, the issue is in this line:
```python
mock_dict = newBall.run_hod(newBall.tracers, want_rsd, write_to_disk, Nthread = 16)
```

This is written as if the third parameter to `run_hod()` is `write_to_disk`, but it's not—it's actually `want_nfw`. So the NFW code path ends up being taken, which ends up breaking due to not being supported with the halo light cones.

You can fix this by simply writing `write_to_disk=write_to_disk` in that line. Arguably we should be enforcing kwarg-only parameters for this function, but I'd rather not break people's code now...

In any case, I'll fix it in the tutorial too. Thanks!

**Comment by danecross** [comment]
That solved the problem! Thanks.
