### ISSUE TITLE
numba TypingError in current main version

### ISSUE THREAD

**Issue by adematti** [abacusorg/abacusutils#164]
Hi,

As I was building a new environment for DESI at NERSC, when trying to read particles, I got the error below, which looks related to commit 2597bbd.
numba version is 0.60.0, same with 0.58.1 (I first assumed a numba version error).

```
Traceback (most recent call last):
  File "/global/u2/a/adematti/cosmodesi/bias/bias/tests/test.py", line 7, in <module>
    abacus_summit.read_data_features(ic=range(2))
  File "/global/u2/a/adematti/cosmodesi/bias/bias/abacus_summit.py", line 194, in read_data_features
    save_data_features(ic=iic, **kwargs)
  File "/global/u2/a/adematti/cosmodesi/bias/bias/abacus_summit.py", line 177, in save_data_features
    final_positions = read_abacus.read_asdf(fn, load=['pos'])['pos']
  File "/global/u2/a/adematti/cosmodesi/abacusutils/abacusnbody/data/read_abacus.py", line 142, in read_asdf
    npos, nvel = unpack_rvint(
  File "/global/u2/a/adematti/cosmodesi/abacusutils/abacusnbody/data/bitpacked.py", line 78, in unpack_rvint
    _unpack_rvint(intdata, boxsize, _posout, _velout)
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20241221-1.0.0/conda/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20241221-1.0.0/conda/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(array(float32, 1d, C), Tuple(int64, Literal[int](0)), float64)
 
There are 16 candidate implementations:
    - Of which 14 did not match due to:
    Overload of function 'setitem': File: <numerous>: Line N/A.
      With argument(s): '(array(float32, 1d, C), UniTuple(int64 x 2), float64)':
     No match.
    - Of which 1 did not match due to:
    Overload in function 'SetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 219.
      With argument(s): '(array(float32, 1d, C), UniTuple(int64 x 2), float64)':
     Rejected as the implementation raised a specific error:
       NumbaTypeError: cannot index array(float32, 1d, C) with 2 indices: UniTuple(int64 x 2)
  raised from /global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20241221-1.0.0/conda/lib/python3.10/site-packages/numba/core/typing/arraydecl.py:131
    - Of which 1 did not match due to:
    Overload in function 'SetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 219.
      With argument(s): '(array(float32, 1d, C), Tuple(int64, Literal[int](0)), float64)':
     Rejected as the implementation raised a specific error:
       NumbaTypeError: cannot index array(float32, 1d, C) with 2 indices: Tuple(int64, Literal[int](0))
  raised from /global/common/software/desi/users/adematti/perlmutter/cosmodesiconda/20241221-1.0.0/conda/lib/python3.10/site-packages/numba/core/typing/arraydecl.py:131

During: typing of setitem at /global/u2/a/adematti/cosmodesi/abacusutils/abacusnbody/data/bitpacked.py (109)

File "../../../abacusutils/abacusnbody/data/bitpacked.py", line 109:
def _unpack_rvint(intdata, boxsize, posout, velout):
    <source elided>
        if posout is not None:
            posout[i, 0] = (intdata[i, 0] >> np.uint32(12)) * posscale
            ^
```

**Comment by lgarrison** [comment]
Could this be due to a difference in numpy versions? I think we're testing against 2.0 or 2.1 right now (can check when I'm back on my laptop later). What version is the new DESI environment targeting?

**Comment by adematti** [comment]
The new environment is using numpy 1.26.4 (due to constraints in the cython version I think)

**Comment by lgarrison** [comment]
I think #165 fixes this. Can you try that?

**Comment by adematti** [comment]
yes, it fixes the issue, thanks for the prompt reply! :)

**Comment by lgarrison** [comment]
Thanks for reporting it!
